-- Prime 60 methodology content. Admin-editable after launch.

insert into public.pattern_library (slug, name, description, replacement, if_then, two_minute_start, sort_order) values
('procrastination', 'Procrastination', 'Putting off the thing that matters, usually for something easier.', 'Start for two minutes.', 'If I notice I am putting it off, then I start the smallest piece for two minutes.', 'Open the document, file or app and do the first physical step.', 1),
('not_finishing', 'Not finishing', 'Starting well and letting things trail off before they are done.', 'Define the next physical action and do only that.', 'If I feel the pull to move on before it is finished, then I write the definition of done and do the next action.', 'Write one line: what does finished look like?', 2),
('starting_too_much', 'Starting too many things', 'Adding new initiatives before current ones are finished.', 'Put it in the Idea Parking Lot.', 'If I have a new idea, then I park it instead of starting it.', 'Open the Parking Lot and write one line.', 3),
('chasing_misaligned', 'Chasing silver bullets', 'Pursuing opportunities that do not serve the five-year vision.', 'Ask: what current priority would this replace?', 'If something shiny appears, then I run it through the six filter questions before touching it.', 'Write the opportunity in one sentence and park it.', 4),
('hiding', 'Hiding when I should be visible', 'Staying quiet, unpublished or in the background when the work needs me seen.', 'Perform one small visible action.', 'If I want to postpone publishing, then I publish the smallest viable version.', 'Turn the camera on and record the opening line.', 5),
('overthinking', 'Overthinking instead of acting', 'Analysing, planning and reconsidering in place of doing.', 'Define the next physical action and do it.', 'If I have been thinking about it for ten minutes, then I do the next physical action.', 'Write the next action in six words and do it.', 6),
('avoiding_conversations', 'Avoiding difficult conversations', 'Letting an important conversation wait because it is uncomfortable.', 'Schedule or start it within 24 hours.', 'If I am avoiding a conversation, then I send the first sentence today.', 'Write the first sentence.', 7),
('approval_seeking', 'Seeking approval', 'Shaping decisions around what others will think.', 'Ask: what do I believe is the right decision?', 'If I notice approval-seeking, then I ask what I would decide if nobody else knew.', 'Write your own answer first, before asking anyone.', 8),
('fear_of_risk', 'Avoiding calculated risk', 'Letting fear decide instead of judgement.', 'Review the evidence and take one concrete step.', 'If fear is the only reason not to act, then I take the smallest real step.', 'List the worst realistic outcome in one line.', 9),
('relationship_drift', 'Letting relationships drift', 'Allowing time to pass without contact with the people who matter.', 'Send the message or make the call.', 'If a relationship is drifting, then I make contact today.', 'Send a short message now.', 10),
('work_over_health', 'Putting work ahead of health', 'Skipping training, sleep or meals for work.', 'Train first, then work.', 'If I am about to skip training for work, then I do the shortest version of the session instead.', 'Put training clothes on.', 11),
('financial_anxiety', 'Letting money worry drive behaviour', 'Making decisions from scarcity rather than strategy.', 'Return to the plan and the next action.', 'If I notice financial anxiety, then I review the numbers and act on one thing within my control.', 'Write the one action that moves income this week.', 12),
('self_doubt', 'Acting from self-doubt', 'Shrinking decisions and ambitions to fit a smaller self-image.', 'Review the evidence and take one concrete action.', 'If I hear self-doubt, then I list three pieces of evidence and act once.', 'Write three things you have already done.', 13),
('comparison', 'Comparing myself with others', 'Measuring progress against other people instead of my own trajectory.', 'Return attention to my own trajectory.', 'If I catch myself comparing, then I open Progress and look at my own line.', 'Open Progress.', 14),
('worrying_what_people_think', 'Worrying what people think', 'Spending energy on imagined judgement.', 'Ask: what would my Prime Self do here?', 'If I am worrying what people think, then I act on what I believe is right.', 'Write the decision you would make if nobody was watching.', 15);

insert into public.courage_rep_types (slug, label, sort_order) values
('published_despite_fear', 'Published despite fear', 1),
('uncomfortable_conversation', 'Had the uncomfortable conversation', 2),
('asked_for_sale', 'Asked for the sale', 3),
('said_no', 'Said no to a distraction', 4),
('finished_before_starting', 'Finished something before starting another', 5),
('shared_opinion', 'Shared an opinion publicly', 6),
('delegated', 'Delegated work', 7),
('calculated_risk', 'Took a calculated risk', 8),
('contacted_someone', 'Contacted someone important', 9),
('acted_despite_uncertainty', 'Acted despite uncertainty', 10);

insert into public.non_negotiable_catalogue (slug, label, pillar, score_key, sort_order) values
('train', 'Train', 'health', 'h1', 1),
('move', 'Move: steps or a walk', 'health', 'h2', 2),
('publish', 'Publish', 'purpose', 'p1', 3),
('connect', 'Connect', 'relationships', 'r1', 4),
('quality_time', 'Quality time, no phones', 'relationships', 'r2', 5),
('finish', 'Finish the one thing', 'identity', 'i1', 6),
('courage', 'One Courage Rep', 'identity', 'i2', 7),
('move_project', 'Move the main project', 'purpose', 'p2', 8),
('serve', 'Serve a client or community member', 'purpose', 'p3', 9);

insert into public.review_questions (section, slug, prompt, sort_order) values
('a', 'a_inevitable', 'Did my behaviour make the Prime Self physique more or less inevitable this week?', 1),
('b', 'b_evidence', 'Did I create evidence this week?', 1),
('c', 'c_best_of_me', 'Who received the best of me this week?', 1),
('c', 'c_felt_important', 'Did the people I love feel important to me this week, or merely know that they are important?', 2),
('d', 'd_avoided', 'What did I avoid?', 1),
('d', 'd_finished', 'What did I finish?', 2),
('d', 'd_overthought', 'Where did I overthink?', 3),
('d', 'd_courage', 'Where did I show courage?', 4),
('d', 'd_approval', 'Where did I seek approval?', 5),
('d', 'd_hid', 'Where did I hide?', 6),
('e', 'e_easier', 'Which behaviour became easier?', 1),
('e', 'e_most_frequent', 'Which unwanted behaviour appeared most?', 2),
('e', 'e_cue', 'What cue triggered it?', 3),
('e', 'e_reward', 'What immediate reward was I seeking?', 4),
('e', 'e_environment', 'How could I redesign the environment?', 5),
('e', 'e_make_easier', 'What should become easier?', 6),
('e', 'e_make_harder', 'What should become harder?', 7),
('e', 'e_identity', 'Which identity did my behaviour reinforce?', 8),
('e', 'e_proved', 'This week I proved I am becoming someone who ______.', 9),
('e', 'e_smallest_change', 'The smallest change with the biggest potential impact next week is ______.', 10),
('f', 'f_priority', 'Biggest priority next week', 1),
('f', 'f_one_thing', 'One thing that must be finished', 2),
('f', 'f_prime_self', 'What would your Prime Self do next?', 3);

insert into public.content_snippets (key, body) values
('score_line_90', 'A Prime Self day.'),
('score_line_70', 'Solid. The man is being built.'),
('score_line_50', 'Mixed day. Return tomorrow.'),
('score_line_0', 'A reset day. One miss is an event. Return tomorrow.'),
('miss_line', 'One miss is an event. Two can become a pattern. Return today.'),
('courage_line', 'Courage Rep recorded. A vote for your Prime Self.'),
('pattern_logged_line', 'Logged. One appearance is information, not a verdict.'),
('vision_quote', 'I didn''t waste it. I became the man I knew I could become.'),
('vision_question', 'Is today''s behaviour worthy of that future?'),
('identity_example_1', 'I am a man who shares his ideas even when it is uncomfortable.'),
('identity_example_2', 'I am someone for whom physical excellence is normal.'),
('identity_example_3', 'I am a father who deliberately invests in his relationships.'),
('identity_example_4', 'I am someone who finishes what he starts.'),
('example_health', 'At 66 I weigh 77 kg at around 11% body fat, year-round. I look mid-forties and move like someone twenty years younger. Training is simply what I do; not training would feel strange. I sleep well, eat with discipline, walk the beach most mornings, and can say without irony that I am in the top 1% physically for my age.'),
('example_purpose', 'I am the recognised front person for a brand that has helped thousands of men reclaim the second half of their lives. A small team and a CEO run the day to day. My work is content, mentoring, speaking, retreats and strategy. Income comes from several machines I built, not from my hours. Money means choice, freedom and the ability to support the people I love.'),
('example_relationships', 'Christine and I are best friends and partners, with deliberate time together, travel, intimacy and peace. My children call because they want to, visit both ways, and are proud of their father. I am present for my family, generous with my friends, and some of the men I mentor have become genuine friends.'),
('example_lifestyle', 'A three-bedroom penthouse on the Gold Coast with the ocean in front of me, and a small place near the Amalfi Coast. Three or four international trips a year, often a month at a time. Fine dining a couple of nights a week. A premium health and longevity club. Golf. A wardrobe that looks like a stylish man in his forties. Luxury as freedom, quality and time, never as display.'),
('example_moment', 'I am sitting on the Amalfi Coast with an espresso, looking across the Mediterranean at the fishing boats. There is stillness. Christine loves and trusts me. My children are proud of me. Thousands of men are better off because of my work. I built financial independence and extraordinary health, repaired what needed repairing, and stopped wasting my potential. I didn''t waste it. I became the man I knew I could become.'),
('stuck_why_fear', 'Fear'),
('stuck_why_uncertainty', 'Uncertainty'),
('stuck_why_complexity', 'Complexity'),
('stuck_why_boredom', 'Boredom'),
('stuck_why_perfectionism', 'Perfectionism'),
('stuck_why_rejection', 'Rejection'),
('stuck_why_difficult_conversation', 'A difficult conversation'),
('stuck_why_dont_know_where_to_begin', 'I don''t know where to begin'),
('stuck_why_other', 'Something else');
